### ISSUE TITLE
MAME 2003 Xtreme WIP

### ISSUE THREAD

**Issue by KMFDManic** [KMFDManic/mame2003-xtreme#36]
Hey, @grant2258 and @arcadez2003 !  The last update went over quite nicely with several hundred plus people.  Amazing how both Plus/Xtreme have really made an impact!  Hope all is well with both of you, and will start going over changes as I throw them in for the Next Update.  I have an Update posting roughly Friday.  But, once that Update posts, it will be entirely focused on doing more updating for Xtreme.  And, @grant2258, I will have to check more into your personal build of MAME 2003, as well.  That may be a cool addition, if you ever want that to make it to the Minis.  One can never have enough MAME:)  arcadez2003 has joined our Discord, and its easy enough to communicate with him there.  It would be cool, as well grant2258, if you joined our Rockin' The Classics Discord.  BS about whatever, as well as Updating here and there.  Or, we can stick to this way, too, whichever you prefer!  I had been pretty busy with work over the last few weeks, so didn't do as much dropping in.

**Comment by KMFDManic** [comment]
And, @gpstar81, hope all is well with you, too!  One thing I discovered since last Update.  I kind of didn't really think about it before.  But, many Arcade Games started on Sharp X68000, complete with CD Soundtracks!  These CD Soundtracks were mostly removed when ported over to the Arcade!  Even stuff like Bubble Bobble sounded amazingly better on Sharp.  Kind of interesting that the Custom OSTs essentially restored what should have never have been removed!  So, I am definitely a big fan of running Arcade and Arcade Quality Games via MAME/FBNEO, and now Sharp X68000:)  Hopefully, all is well with you!  We shaped up MAME 2003 Xtreme to be quite nice over the last few Updates.  If you need a current build for the Minis, feel free to drop in anytime, and I will send you one!  Otherwise, stay safe!

**Comment by ghost** [comment]
its not a problem popping in when if something needs discussed at all. I generally try to stay away from dev stuff and hangouts after experiencing the murkier side of it. I think arcadez built a good base for mame2003-plus.

My build isint completely finished it just finding the motivation since its for myself im less motivated because i dont really use gamepads on my barcade i havent got round to doing the gamepad mappings. Ill try get some of auto mapping done at the weekend. Most of what i addressed is removing needless complication in setup and made the tab menu be used like standalone and returned the information screens when you pick a non working games. The rest is just background stuff.

I did send you update to your mame2010 repo to fix the input stuff not sure if its any good for your hardware though regardless if a better mini comes out it should work for you if you want to use it

things are going fine here thanks for asking hope all is well in your parts. The only issue I have is its too damn hot here at the moment. We hard ever get great weather and it decides to come during a pandemic of all things!

**Comment by KMFDManic** [comment]
@grant2258 As of now, was adding the Hunting and Golfing Games to MAME 2003 Xtreme, and got this as compile error:

anonymous version tag cannot be combined with other version tags
collect2: error: ld returned 1 exit status
Makefile:541: recipe for target 'km_mame2003_xtreme_libretro.so' failed

The exact files arcadez2003 sent me are attached.  It may simply be relative to my compiler set-up.  I just haven't pinpointed it yet.  Once I get my latest Update out, it will be easier to focus on it.

[Hunting And Golfing.zip](https://github.com/KMFDManic/mame2003-xtreme/files/4795490/Hunting.And.Golfing.zip)

Motivation is definitely a thing, especially with the crazy things going on in the World, this year!  One thing to the next!  Corona, Lockdowns, Rioting in USA, list goes on.

**Comment by ghost** [comment]
looks like a linker error havent see that one before. Try a make clean and compile again if you havent tired that already will compile it here and see if it works.

edit: compiled fine here on linux and windows added a pull request. 

well there is trump for you guys and we have borris lets face it thats is a bad as it gets lol

**Comment by gpstar81** [comment]
I am well. I am actually on vacation at the moment. Much needed after the 3 month confinement we had here.

**Comment by KMFDManic** [comment]
@grant2258 Not sure how I didn't notice you threw in that pull request!  I usually get Email Notifications.  What would be really cool is if you joined the Discord I am in, so we can just bs on the fly at times.  Arcadez joined and we have been chatting occasionally.  How are things going with you, anyways?  I caught up with work, had to take care of some real life reality bs, such as ants, car problems, all that fun stuff.  But, I finally was able to get a little stuff in, such as Orville.  I tried doing Star Trek Picard on CBS, and found it not as great as the original TNG.  But, then I did Orville, and found that more endearing.  It was kind of a mix of The Original Star Trek, TNG, and some of the usual humor you might expect from Family Guy and American Dad, albeit very lightly used!

@arcadez2003 Thanks again for your help in getting some of these coding additions implemented!  What have you been watching or up to?

I will do a compile test, and get back to you guys by tomorrow.  Have to work shortly.

**Comment by ghost** [comment]
Ive seen Picard I thought it was watchable but very different to any other star trek. I hear you on the car I have one thing left to do on mine. I seen my controls arms have seen better days so i changed them. After I dont that measured the ride height and it was uneven had a snapped tail on the top of the spring drivers spring. So i changed that and the drop links while I was at it(only because they where rusted up and had to be cut off to do the spring). The the usual thing with cars i went to adjust the wheel alignment so i could drive down to the garage and get it aligned. Yea you guessed it the where rusted in good not even moving with a tourch. I have new inner and outer tie rod ends will put them in when the weather clears up a bit been raining the last few days and im not too motivated as ive got two cars for times like this so i always have access to one! I usually only check forums and redit now and then. If there is some issue that does need thrashed out gimme a shout!

**Comment by KMFDManic** [comment]
@grant2258 My car has had its own fun share of issues.  Wheel bearing replaced, had someone help on replacing the power steering hose pressure line.  They unintentionally broke a sensor and damaged the return line when attempting to dislodge the "fused" pressure line, which is a common problem on my model of car.  I ended up letting a shop finish it up, and they were very easygoing and quite nice with me.  I have generally bought my own parts so it kept the cost down at shops, and for 20 plus years never had an issue.  But, this time, the pressure line I got ended up being not properly crimped...So, the moment they installed it and turned the car on, after it was back together, it exploded at the bad crimped end, shooting power steering fluid everywhere.  They told me this stuff can happen occasionally.  But, with their supplier of parts, if it does, they get reimbursed for labor costs.  

In the end, they ended up being very nice to me and giving me a good deal, on fixing up the pressure line, replacing return line and sensor that were both previously damaged.  I still need to replace my right wheel bearing, and brake pads, and maybe get some new tires.  And, you know how things go...moment you get all fixed, you end up needing another car, anyways, hehe.

Hope all is well with you.  I still get the anonymous version tag for the Minis, so it is likely due to something in my compiler setup.  I will still poke at it.  But, for now, I am gonna play around with a few other additions.

Also, I started watching the show Lucifer, not too bad a show.  I checked out your other recommendations!  And, they were fun.  Feel free to suggest anything else.  

If you ever wanna bs more directly, you are welcome to hop onto Discord, and join our channel.  Arcadez2003 pops in to chat.

**Comment by KMFDManic** [comment]
@arcadez2003 @grant2258 I fixed my compiler errors, and am able to get what I needed in.  It was due to anonymous version tags not being supported when I updated other things so that I could compile a few other Cores, etc.  In any case, Hunting/Shooting are good to go.  I also decided I wanted to add the Model 1 Support, particularly for Virtua Fighter 1.  I got it up and running, working.  I just need to fix up the speed.  Hopefully, one of you can enlighten me onto what I may still need to finish up.

**Comment by KMFDManic** [comment]
@grant2258 Everything is in order, now:)  Arcadez2003 helped with a few of the last minute details!  All exceptional now!  Be sure to keep in touch:)

**Comment by ghost** [comment]
morning was lovely weather here yesterday. Glad you got it fixed he did port that driver he would be the best person to fix it. Sorry i missed you message until now.

**Comment by KMFDManic** [comment]
@grant2258 @arcadez2003 Both the hunting and golf games are running perfectly.  Most I may need to do with them is adjust sensitivity.  But, they are still quite playable!  You both stay safe.  And, I will continue adding other stuff to Xtreme, since it really benefits the Mini Classic Users.  The bootstrap additions will go over very well, too!  Arcadez2003 recommended a cool Wrestling show called Dark Side of the Ring...Stories that really show the darker side of the glorious sport of Wrestling!  Some stuff I never knew, growing up!

And, with some of the more current shows slowing down, due to production ceasing, due to Corona and such...I actually started going back to some childhood shows, including the Greatest American Hero.  Haha.  I can see Airwolf being another fun show to redo!
