### ISSUE TITLE
[Feature Request] When you turn TATE mode ON — perform a swap/flip on the screen HEIGHT x WIDTH

### ISSUE THREAD

**Issue by giovanifaganello** [KMFDManic/mame2003-xtreme#38]
Hey, KM!

I started [this topic](https://github.com/libretro/RetroArch/issues/11279) this morning and people pointed me here.

My request is simple — when we do open a MAME game and turn the TATE mode ON (in-game options) the screen rotates to vertical mode (ok, all correct) but the WIDTH and HEIGHT does not, presenting then a distorted game play screen. Is it possible to SWAP/FLIP the WxH values while TATE is ON? When TATE toggle off, the values get back to its normal, as recorded on the game very own RGUI/MAME-2003-XTREME/game.cfg.

Notice: I am using video scaling on CUSTOM, size 3X with INTEGER ON — RetroArch 1.9.0 PlayStation Classic with RetroBoot Stand Alone.

Do you think it is feasible?

**Comment by ghost** [comment]
See the problem is as far as arcades go the x and y are what they should be they physically rotate the monitor. It also best not to use integer scaling you end up with bad resolutions as crt pixels arent a perfect size for a 1 to one plot it just happens a crt is 4:3 or 16:9 so it scales properly. RA front end does not update geometry when rotated you would need to request that feature from them. 

The thing you need to keep in mind is tate mode is 4:3 its the monitor that is physically rotated  so it is a 4:3 resolution. What tate mode does right now is a counter clock wise rotation the reason for this is some arcades where rotated clock wise and some counter clock wise. So what you need to keep in mind is the only time a rotation happens is when tate mode is off or its clock wise. Hope this helps a little. I might add more tate mode Rotation options if Kdmfmanic wants them currently we only have ccw some people may require cw as well because there stand only rotates one direction again it will be up to the big man if he wants this feature or not it is simple enough to implement. Im not the best for explaining things but if you have a specific question ill do my best.

**Comment by giovanifaganello** [comment]
> See the problem is as far as arcades go the x and y are what they should be they physically rotate the monitor.

First, thank you, Grant!

But I forgot yo mention... My 42 inches LG led screen rotates on the wall! I did setup it exactly to be able to play vertical shmups really on a vertical fashion. I really don't see the point of TATE if it just rotates the screen but not the coordinates... At same time I believe that, with video scaling on CORE (instead of custom) would then rotate the screen too, since the screen size is coming from the core, is that correct?

For the direction of rotation, it is perfect as it is now. I have tested more than 100 vertical games on TATE and all are perfect... but, obviously, I went game by game, in their CFG files, and flipped/swapped the WIDTH x HEIGHT manually. But sometimes I take my PSClassic to my friends house and their TVs does not rotate. So I need to go to the CFG files and revert the changes.

All could be solved by RA's swapping values when TATE is ON, maybe by checking the flag of INTEGER SCALING = TRUE?

In my opinion INTEGER scaling is the best thing out there since they discovered the wheel. My setup has around 700 mame games neatly adjusted using perfect width and height right from each game technical info, and adding a scanline overlay things are absolutely amazing. Also, bilinear OFF, of course.

And finally, if you say it is something related to the RA interface guys, I will keep the thread alive over there. Someone told me this could be directly related to the MAME core itself.

Talking about MAME core, just updated my PSClassic RA (that uses KFMD stuff) and the game ALCON is not running anymore on MAME-20030-xtreme. It loads fine, but got a HW ERROR on screen (a game message, not a MAME or RA one). Does it happen to you?

**Comment by ghost** [comment]
Well mame extreme and 2003/plus user ra for rotations that it can do if it doesnt support others like mirroring it does it internally. 

Let me try explain it this way mame doesnt need any rotation for vertical games its a normal 4:3 that is physically rotated only some are twisted another way so mame makes sure all vertical games go counter clockwise. That aside the either way and treated as a 4:3 like it is in an arcade cab its just rotated physically. 

If tate mode is off thats changing everything to the monitor you are using its making is basically 3:4 applied rotation applied to your current display.  Im not familiar with that game at all. Im not sure if there is any issues with that game am fixing the car today will try later if i get the chance.

edit 

sometimes a picture will say a 1000 words this is how a vertical game would render in a arcade normal cabinet that didnt have its screen physical rotated in the cabinet like vertical cabinets do. 

![batsugun-200905-191524](https://user-images.githubusercontent.com/6128601/92311210-07f37d80-efad-11ea-9bf7-4f74e009bbc8.png)
 
as you can see its clear rendered at 4:3 but drawn sideways natively (tate mode on). For tate mode off it just does the rotation to your current display geometry instead of the native render for people that dont want to twist there monitor round. 

I looked into you problem with alcon. I know the game as slapfight and the good news is arcadez has fixed it in 2003 plus here all that needs done is to be ported over to extreme.  https://github.com/libretro/mame2003-plus-libretro/commit/77f6547147d9058a47c4be2a2e0ae0f89ba1bdfc#diff-e7734dabb6fe81b28b89724eb0517397 in not sure what the policy is on rom changes in this core though.

**Comment by DSkywalk** [comment]
I fixed vertical games with this little fix, from mame2003-plus:

```
--- src/libretro/video.c	2023-11-30 05:07:42.046416000 -0500
+++ src/libretro/video-fixed.c	2023-12-03 16:17:08.667883240 -0500
@@ -153,6 +153,7 @@
    }
 
    /* Set up native orientation flags that aren't handled by libretro */
+   if (orientation & ORIENTATION_SWAP_XY) video_hw_transpose = true; /*dont set this to false if RA changes the flags else vertical games swap the xy*/
    video_flip_x = orientation & ORIENTATION_FLIP_X;
    video_flip_y = orientation & ORIENTATION_FLIP_Y;
    video_swap_xy = orientation & ORIENTATION_SWAP_XY;
```

Because the aspect is not correctly reported to the UI.

```
1942 (plus):
256 x 224 (V) 60.000000 Hz
[INFO] aspect_ratio: 0.750000 fps: 60.000000
[INFO] selectScaler
[INFO] aspect: 360x298 (0.750000)
[INFO] aspect: 0.750000
[INFO] coreAR:0.750 fixedAR:1.333 srcAR: 0.875
name:aspect3P
fit:0 scale:3
src_x:0 src_y:0 src_w:224 src_h:256 src_p:448
dst_x:260 dst_y:0 dst_w:1192 dst_h:768 dst_p:2384
aspect_w:360 aspect_h:298

1942 (extreme):
[INFO] aspect: 1.333333
[INFO] selectScaler
[INFO] aspect: 342x256 (1.333333)
[INFO] aspect: 1.333333
[INFO] coreAR:1.333 fixedAR:1.333 srcAR: 0.875
name:aspect3M
fit:0 scale:3
src_x:0 src_y:0 src_w:224 src_h:256 src_p:448
dst_x:0 dst_y:0 dst_w:672 dst_h:768 dst_p:1344
aspect_w:342 aspect_h:256
``` 
Cu! :)

**Comment by KMFDManic** [comment]
@giovanifaganello Hopefully, with the help of bslenul, and other responses, you are in a better place regarding your overall setup, tate mode wise, now.  If there is anything else of interest to you, I could generally port the fixes over to this Core, within reason.  The Plus Team has always been quite gracious as far as enlightening me with insight, where applicable, too:)

@DSkywalk One of the very first things I got into, when I got into the emulation scene, with the Mini Classics, was your work on the CPC Amstrad Core.  Nice to see you are still going quite strong with what you do!  Xtreme/Plus will consistently update, to adapt to new fun variables.  I will be updating Cores for the Minis in the fairly near future, and will be sure to get CPC updated, too:)  I played Dragon's Lair port on that, previous to finally getting Coleco SGM version going with dinkc64 and company.  The hardest part of Coleco SGM was actually "being able to dump" the games, to properly include them in the coding, hehe:)  But, we now have pretty much all of the known dumps within FBNEO.  And, I will be posting 2 other Cores that can play SGM, too.  

@
